### ISSUE TITLE
No config file for 1.15.2

### ISSUE THREAD

**Issue by zeeoric** [henkelmax/advanced-mining-dimension#1]
I added for minecraft version 1.15.2 the version 1.0.6 but there is no config file.  I was hoping to be able to use the config file because many of the ores are not spawning.  I have spent 30 mins playing in this dimension and only found coal, Imperium and Wum Wum ore.  I have not even been able to find Iron, gold or many other common ores.

**Comment by henkelmax** [comment]
Have you read the FAQ?
https://modrepo.de/minecraft/mining_dimension/faq

**Comment by zeeoric** [comment]
you mean where it states "The client side config is located in your '.minecraft' folder inside a subfolder called 'config'."

I made an entire new client and only added this mod and i have the fml and forge-client configs but no mining dimension config.

here is a list of everything in my config file on the mod pack I am working on.  I do not see any mining dimension config file anywhere.


Name | Size | Date Modified
-- | -- | --
fancymenu/ |   | 8/10/20, 1:21:19 PM
fpsreducer/ |   | 8/10/20, 1:21:19 PM
industrialforegoing/ |   | 8/10/20, 1:21:19 PM
jei/ |   | 8/10/20, 12:43:13 PM
Mekanism/ |   | 8/10/20, 1:52:20 PM
ProjectE/ |   | 8/10/20, 1:21:19 PM
titanium/ |   | 8/10/20, 1:21:19 PM
waila/ |   | 8/10/20, 1:21:19 PM
appleskin-client.toml | 844 B | 8/10/20, 3:57:20 PM
bettertitlescreen-client.toml | 539 B | 8/2/20, 8:32:32 PM
bonsaitrees2-client.toml | 102 B | 8/10/20, 3:57:20 PM
bonsaitrees2-common.toml | 361 B | 8/10/20, 3:57:20 PM
botanypots-client.toml | 343 B | 8/10/20, 3:57:20 PM
cookingforblockheads-client.toml | 127 B | 8/10/20, 3:57:20 PM
cookingforblockheads-common.toml | 1.1 kB | 8/10/20, 3:57:20 PM
cucumber-client.toml | 115 B | 8/10/20, 3:57:20 PM
cucumber-tags.json | 988 B | 8/10/20, 4:00:36 PM
cyclic.toml | 2.3 kB | 8/10/20, 2:42:23 PM
doggytalents-client.toml | 690 B | 8/10/20, 3:57:20 PM
fml.toml | 242 B | 8/10/20, 3:57:06 PM
forge-client.toml | 1.2 kB | 8/10/20, 3:57:20 PM
journeymap_ModInfo.cfg | 373 B | 8/10/20, 12:46:05 PM
journeymap-common.toml | 529 B | 8/10/20, 3:57:20 PM
MouseTweaks.cfg | 135 B | 8/2/20, 8:32:32 PM
mysticalagriculture-client.toml | 137 B | 8/10/20, 3:57:20 PM
mysticalagriculture-common.toml | 1.7 kB | 8/10/20, 3:57:20 PM
neat-client.toml | 949 B | 8/10/20, 3:57:20 PM
oreexcavation_groups.json | 1.1 kB | 8/2/20, 8:32:32 PM
oreexcavation_overrides.json | 204 B | 8/2/20, 8:32:32 PM
oreexcavation_shapes.json | 566 B | 8/2/20, 8:32:32 PM
oreexcavation-client.toml | 286 B | 8/10/20, 3:57:20 PM
oreexcavation-common.toml | 1.5 kB | 8/10/20, 3:57:20 PM
overloaded-client.toml | 351 B | 8/10/20, 3:57:20 PM
overloaded-common.toml | 495 B | 8/10/20, 3:57:20 PM
pickletweaks-client.toml | 166 B | 8/10/20, 3:57:20 PM
pickletweaks-common.toml | 2.1 kB | 8/10/20, 3:57:20 PM
storagedrawers-common.toml | 939 B | 8/10/20, 3:57:20 PM
storagenetwork.toml | 642 B | 8/10/20, 2:42:29 PM
tinymobfarm.toml | 321 B | 8/10/20, 3:57:20 PM
tp-common.toml | 14.4 kB | 8/10/20, 3:57:20 PM
treegrowingsimulator-common.toml | 199 B | 8/10/20, 3:57:20 PM
vehicle-client.toml | 1.8 kB | 8/2/20, 8:32:32 PM

**Comment by zeeoric** [comment]
I tried 1.15.2 version 1.0.4 and 1.0.6 both, neither seem to create a config file for me, and i have tried in multiple mod packs even blank ones.

**Comment by henkelmax** [comment]
This mod only creates a server config.

**Comment by zeeoric** [comment]
single player still creates a local server host, but is not creating a config file

**Comment by henkelmax** [comment]
```The config for the server side is located in your world folder in a subfolder called 'serverconfig'.```
