### ISSUE TITLE
[1.16.3] Receipe does not shows up in receipe book (vanilla)

### ISSUE THREAD

**Issue by realTIMematrix** [henkelmax/advanced-mining-dimension#10]
**Please read the [FAQ](https://modrepo.de/minecraft/mining_dimension/faq) before submitting a bug report!**

**Bug description**
Receipe for Mining Dimension Block does not show up in receipe book, don't want to use JEI.

**Steps to reproduce the issue**
1. Start fresh Game
2. get some wood and stone
3. craft related items like stone pickaxe, craftingtable and wood
4. no receipe appears in vanilla receipe book

**Expected behavior**
After crafting a stone pickaxe I would expect I have all materials for this items but it does not shows up. It will be shown AFTER you craft one of this teleporter, but if you don't know the receipe and don't use JEI (because there is no JEI for 1.16.3) you are lost. 

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version 1.16.13
- Forge version 34.0.9
- Mod version 1.0.1

**Other mods**
no other mods installed

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Thanks for reporting this issue. It should be fixed in the latest version.
