### ISSUE TITLE
Vanishing XP

### ISSUE THREAD

**Issue by bblewitt** [henkelmax/advanced-mining-dimension#12]
**Bug description**

XP points and levels vanishes on the dimension load to the mining dimension and back to the overworld in any config of the world type. (Superflat, Default, ect...) but returns to normal when gaining XP points from an orb or command giving.

**Steps to reproduce the issue**

1. Load up the world
2. Do /xp add "player_name" 10 levels
3. Enter the mining dimension from the teleporter block (vanishes xp)
4. Do step 2 again and it should say 20
5. Enter the overworld from the teleporter block (vanishes xp)

**Expected behavior**

On entering the dimension the xp should disappear from screen.
Such as entering the nether or end. From or to.

**Log files**

[Logs](https://paste.ee/p/EVbFP)

**Versions**

- Minecraft version 1.16.3
- Forge version 34.1.0
- Mod version 1.16.3-1.0.2

**Other mods**

This can happen on a blank dev client or forge installed client with just the mining dimension installed as well.
[List of mods installed](https://paste.ee/p/PXdao)

**Comment by henkelmax** [comment]
Thank you for reporting this issue!
