### ISSUE TITLE
[1.16.3] Datapacks on server

### ISSUE THREAD

**Issue by YOYOK9** [henkelmax/advanced-mining-dimension#15]
Hello,
Would it be possible to get some help on this. I've started running out of ideas to try. 

I've been trying to figure out how to get this working on my server. Currently I have tried:
1) Coping a client side world to the server (remote desktop) in the dimensions folder
2) Creating a new world with the mod installed to see if it will generate a file in the dimensions folder
3) Using the more_ores datapack and letting the server boot with it, then using the /datapack enable "file/more_ores" after "file/bluepower" to well enable it. Server spat out "alread enabled" even after a reboot

At this point none of these have actually created a folder within the dims folder. And clicking the portal block results in nothing (client or server) 
I tried option 3 client side and it worked no problem...

Only thing I haven't tried is creating the client side world directly on the host machine, but that would involve needing to install a client and such. 

Datapack dir: \world\datapack\more_ores\data(ect) and the pack.mcmeta file. 

MC: 1.16.3
Forge: 34.1.23
mining_dimension-1.16.3-1.0.5.jar

**Comment by henkelmax** [comment]
Please have a look at issue #14 

https://github.com/henkelmax/advanced-mining-dimension/issues/14#issuecomment-707924771

> I copied the "dimensions" folder from the locally ran world to the server world. I'm now able to join the dimension.
