### ISSUE TITLE
[1.16.3] Config options missing? (gone in newer updates.)

### ISSUE THREAD

**Issue by Gbergz** [henkelmax/advanced-mining-dimension#16]
**Bug description**
Server config & normal config are missing their config options that were available not too long ago.
This config specifically, no longer works: _(uploaded as .txt because .toml isn't supported here.)_
[mining_dimension-server.txt](https://github.com/henkelmax/advanced-mining-dimension/files/5496128/mining_dimension-server.txt)

Now this is the new one, with none of the previous options:
[mining_dimension-server.txt](https://github.com/henkelmax/advanced-mining-dimension/files/5496130/mining_dimension-server.txt)

**Expected behavior**
That the config worked like it did in previous versions.

**Versions**
- Minecraft version: 1.16.3
- Forge version: 34.1.25
- Mod version: [mining_dimension-1.16.3-1.0.5](https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension/files/3074922)

**Comment by henkelmax** [comment]
Please just read the mods description.

**Comment by Gbergz** [comment]
Must've missed that part, was used to it being in the serverconfig. Thanks
