### ISSUE TITLE
Forge 35.0.15 Server + BiomesOPlenty error

### ISSUE THREAD

**Issue by MachinegunMarty** [henkelmax/advanced-mining-dimension#17]
I'm running:
forge-35.0.15 Server and Client
Mining World 1.16.4-1.0.1 + more_ores datapack
BiomesOPlenty-1.16.4-13.0.0.420-universal.jar

I have an existing 1.16.4 world and added the latest advanced mining dimension + more_ores datapack.

If i place the teleporter i get the message: The mining Dimension hasn't been created yet.

This is on an existing world.

I rebooted my server 2 times, but still no mining dimension was created.
After removing the datapack, the dimension got created and i could enter it.

I shutdown the server and added the datapack again.

Now the server crashed.

So I removed the datapack again - Server crashed
I removed the dimension folder - Server crash
I removed the advanced mining mod - Server crash

Can't start the server anymore. 

In all the logs since the crash it's something about BiomesOPlenty causing it.
I Will report it there to.

_Originally posted by @MachinegunMarty in https://github.com/henkelmax/advanced-mining-dimension/issues/14#issuecomment-725644214_

**Comment by MachinegunMarty** [comment]
Found a fix:

https://github.com/AllTheMods/ATM-6/issues/258#issuecomment-723029394

So in short: I edited my server.properties and changed: level-type=biomesoplenty to level-type=default.
Now the server starts again.

I shutdown the server and added advanced mining dimensions again and the "more_ores" datapack folder.
The server started, but no dimension got created.
I removed the datapack folder, started the server and the dimension folder got created.

To test:
I zipped the more_ores folder and placed the .zip in the datapacks folder and threw the dimension folder away.

The server started and the dimension folder got created.

I don't know if all the custom ores i added in the mining.json are also spawning in the dimension. I have to test that to see.

**Comment by henkelmax** [comment]
Alright, let me know if you find the issue.
Can you send me the logs of the biomes o plenty crash?
Maybe this helps finding a solution.

**Comment by MachinegunMarty** [comment]
[2020-11-11-25.log](https://github.com/henkelmax/advanced-mining-dimension/files/5529664/2020-11-11-25.log)

Sure man. This is the log from the first time the server crashed.

I will test now if the datapacks work if you zipped them.

**Comment by MachinegunMarty** [comment]
I'm sorry man, it's not the datapack.

I added some custom ores to mining.json and something threw an error in the server logs.
So i was testing with a bad datapack all along grrr.

So i used your original more_ores datapack now and it generates a mining world now.

So the dimension generating problems are gone now with forge 35.0.15 and 1.0.1 version of mining dimensions !

So this issue can be closed because this is on BiomesOPlenty's side. BOP has trouble with mods making dimensions.

I will make a new issue for the datapack seeing that allot of people have issues with that.

**Comment by henkelmax** [comment]
Thanks for letting me know!
