### ISSUE TITLE
1.16.4 Server - Adding custom ores to datapack not working and stopping dimension from being created

### ISSUE THREAD

**Issue by MachinegunMarty** [henkelmax/advanced-mining-dimension#18]
**Please read the [FAQ](https://modrepo.de/minecraft/mining_dimension/faq) before submitting a bug report!**

**Bug description**
On a server using a the more_ores datapack and adding custom ores to mining.json doesn't work and prevents dimension from being created.

**Steps to reproduce the issue**
1. Throw away the dimension folder on server
2. Add an adjusted more_ores datapack (can be the folder or a .zip)
3. Start Server
4. See no dimension folder get's created
5. Run "/datapack list enabled" from client and see [file/more_ores.zip (world)
6. Shutdown Server
7. Remove datapack
8. Start server and see that dimension folder get's created.

**Expected behavior**
Make a new mining dimension with the setting set in the datapack. 
(no monsters and added ores from other mods)

**Log files**
[main/ERROR] [net.minecraft.util.registry.DynamicRegistries/]: Error loading registry data: Failed to parse mining_dimension:worldgen/biome/mining.json file: com.google.gson.stream.MalformedJsonException: Unterminated array at line 42 column 8 path $.features[0][18]
[main/ERROR] [net.minecraft.world.storage.SaveFormat/]: WorldGenSettings: Failed to parse mining_dimension:worldgen/biome/mining.json file: com.google.gson.stream.MalformedJsonException: Unterminated array at line 42 column 8 path $.features[0][18]

**Versions**
- Minecraft version: 1.16.4
- Forge version: release.16.4-forge-35.0.15
- Mod version: mining_dimension-1.16.4-1.0.1

**Other mods**
BiomesOPlenty: Set the level-type=default now so that biomesoplenty doesn't interfere.

Powah: Generates Ores
Mekanism: Generates Ores
Thermal Expansion: Generates Ores
Extreme Reactors 2: Generates Ores
Gobber2: Generates Ores

Weird thing is tho:
Generating a mining dimension (without Datapack) i DO get:
Mekanism ores and Powah ores spawning in the mining world ??

Thermal, Gobber2  and ExtremeReactors2 ores are not spawning.
Back in the BigReactors day you had to add dimensions to BigReactor config in order for yellorite to spawn there.
I don't see that config option in ExtremeReactors2 tho. Not on client or server.

Gonna try and ad them one by one and see where it goes wrong.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
I did your steps to reproduce, but it works fine for me.
Does this happen if you have no other mods installed?

**Comment by MachinegunMarty** [comment]
Been testing and wanted to give an update:

If i use your original "more_ores" it works.
In the mining.json this is the standard features listed:

"features": [
    [
      "minecraft:lake_water",
      "minecraft:lake_lava",
      "minecraft:monster_room",
      "minecraft:ore_dirt",
      "minecraft:ore_gravel",
      "minecraft:ore_granite",
      "minecraft:ore_diorite",
      "minecraft:ore_andesite",
      "mining_dimension:ore_coal",
      "mining_dimension:ore_iron",
      "mining_dimension:ore_gold",
      "mining_dimension:ore_redstone",
      "mining_dimension:ore_diamond",
      "mining_dimension:ore_lapis",
      "mining_dimension:ore_emerald",
      "minecraft:disk_sand",
      "minecraft:disk_clay",
      "minecraft:disk_gravel"
      ]

I added  "thermal:apatite_ore" to the json like this:

      "minecraft:disk_clay",
      "minecraft:disk_gravel"
      "thermal:apatite_ore"
      ]

Removed the Dimension folder, Started the server and it threw this error:

[main/ERROR] [minecraft/DynamicRegistries]: Error loading registry data: Failed to parse mining_dimension:worldgen/biome/mining.json file: com.google.gson.stream.MalformedJsonException: Unterminated array at line 42 column 5 path $.features[0][18]
[main/ERROR] [minecraft/SaveFormat]: WorldGenSettings: Failed to parse mining_dimension:worldgen/biome/mining.json file: com.google.gson.stream.MalformedJsonException: Unterminated array at line 42 column 5 path $.features[0][18] missed input: {"mining_dimension:mining":{generator:{settings:"mining_dimension:mining",seed:0L,biome_source:{biome:"mining_dimension:mining",type:"minecraft:fixed"},type:"minecraft:noise"},type:"mining_dimension:mining"}}; Failed to parse mining_dimension:worldgen/biome/mining.json file: com.google.gson.stream.MalformedJsonException: Unterminated array at line 42 column 5 path $.features[0][18]

This error is because i didn't put a ,(comma) behind the gravel line - right ? (correct me if i'm wrong pls)
No dimension folder got created.


now i changed the json to:

      "minecraft:disk_clay",
      "minecraft:disk_gravel",
      "thermal:apatite_ore"
	]

Started the server and now i get this error:

[main/ERROR] [minecraft/BiomeGenerationSettings]: Feature: Not a JSON object: "thermal:apatite_ore"; Not a JSON object: "minecraft:disk_gravel"; Not a JSON object: "minecraft:disk_clay"; Not a JSON object: "minecraft:disk_sand"; Not a JSON object: "mining_dimension:ore_emerald"; Not a JSON object: "mining_dimension:ore_lapis"; Not a JSON object: "mining_dimension:ore_diamond"; Not a JSON object: "mining_dimension:ore_redstone"; Not a JSON object: "mining_dimension:ore_gold"; Not a JSON object: "mining_dimension:ore_iron"; Not a JSON object: "mining_dimension:ore_coal"; Not a JSON object: "minecraft:ore_andesite"; Not a JSON object: "minecraft:ore_diorite"; Not a JSON object: "minecraft:ore_granite"; Not a JSON object: "minecraft:ore_gravel"; Not a JSON object: "minecraft:ore_dirt"; Not a JSON object: "minecraft:monster_room"; Not a JSON object: "minecraft:lake_lava"; Not a JSON object: "minecraft:lake_water"

A dimension was made tho, but i spawned at y level 3 and no ores have spawned. It's made completely out of stone.
The only ores i see that did spawn are mekanism and powah ores, but no coal or iron and such ?

I can give you my complete modlist, but the 5 mods above are the only one's that spawn in ores.

**Comment by henkelmax** [comment]
That's not a bug, you are not understanding how custom dimensions work. You can't just add random block IDs to the features. You have to add it to https://github.com/henkelmax/advanced-mining-dimension/tree/master/datapacks/more_ores/data/mining_dimension/worldgen/configured_feature
