### ISSUE TITLE
Vanilla Ores Don't Spawn

### ISSUE THREAD

**Issue by M1dnightRid3r** [henkelmax/advanced-mining-dimension#20]
I recently got this mod on my hardcore world that I was playing and when I go in to the mining dimension, it has no vanilla ores at all except for ores from mods (eg. Pattysmorestuff, More Ores In ONE). I was tired of mining without finding anything so I opened to LAN and went  on spectator mode and it was true, no vanilla ores, only modded ones

**Comment by henkelmax** [comment]
Please use the provided issue template
