### ISSUE TITLE
Vanilla Ores Don't Spawn

### ISSUE THREAD

**Issue by M1dnightRid3r** [henkelmax/advanced-mining-dimension#21]
**Please read the [FAQ](https://modrepo.de/minecraft/mining_dimension/faq) before submitting a bug report!**

**Bug description**
No Vanilla Mods spawn in the world, Only modded Ores

**Steps to reproduce the issue**
2. Click on '...'
3. Scroll down to '...'
i dont understand this ^^

**Expected behavior**
I expected every ore in the game to be in the mining dimension

**Log files**
https://gist.github.com/M1dnightRid3r/37c643e83823a73e861cc83bf75e0d0d

**Versions**
Forge Version - 1.16.1

**Other mods**
Quark, More Ores in One, Pattysmorestuff, Biomes O Plenty, Aquaculture, Abnormals Core, AutoRegLib, Bookshelf, Buzzier Bees, Collective, EnderiteMod, Extra Boats, Fast Leaf Decay, FishTraps, Gravestone, HWYLA, Iron Chests, Iron Barrels, JEI, JRFTL, Just Enough Resources, KleeSlabs, MCW Bridges, MCW Doors, MixInBootstrap, NaturesCompass, Optifine, ProductiveBees, QuantumStorage, Softer Hay Bales, Supplementaries, The Endergetic Expansion, Travelers Backpack, Uppers, Wallpaper Craft, WAWLA, Xaeros Minimap, Xaeros World Map

**Comment by henkelmax** [comment]
I'm sorry, but I don't support 1.16.1 anymore. Please consider updating to newer versions.
