### ISSUE TITLE
How to install one of the example datapacks?

### ISSUE THREAD

**Issue by kdog720** [henkelmax/advanced-mining-dimension#25]
I'm not good with Github, and I'm also new to the whole data pack thing. This there any way to have a video or step by step guild on installing some of the example data packs.

**Comment by henkelmax** [comment]
1. In the repository click on `Code` and then on `Download Zip`

![image](https://user-images.githubusercontent.com/13237524/101144515-b9d82f80-3618-11eb-98da-363cf5a5b9a7.png)

2. Extract the .zip file and navigate to `advanced-mining-dimension-master.zip/advanced-mining-dimension-master/datapacks`

3. Open Minecraft and create a new world

4. Click on `Data Packs`

![image](https://user-images.githubusercontent.com/13237524/101145572-4505f500-361a-11eb-9dec-3615a62bc415.png)

5. Click on `Open Pack Folder`

![image](https://user-images.githubusercontent.com/13237524/101145671-6666e100-361a-11eb-896a-817dfbdd04f4.png)

6. Drag the datapack folder you want from the .zip file into the window that just opened

7. Now something should appear on the left side

![image](https://user-images.githubusercontent.com/13237524/101145834-9dd58d80-361a-11eb-9640-4eaa1dd95607.png)

8. Click on the icon of the datapack

![image](https://user-images.githubusercontent.com/13237524/101146010-cbbad200-361a-11eb-8e07-168b51a1778a.png)

9. Click on `Done`

![image](https://user-images.githubusercontent.com/13237524/101146048-d70dfd80-361a-11eb-96ea-cda370753a32.png)
