### ISSUE TITLE
Suggestion: Gobber 2 compatibility

### ISSUE THREAD

**Issue by Knito58** [henkelmax/advanced-mining-dimension#29]
**Is your feature request related to a problem? Please describe.**
Gobber ore is not within the mining dimension. Powah's urananite ores are, though. Also copper from router reborn.

**Describe the solution you'd like**
Gobber ore (overworld version) would be nice.

Thank you, that mod is great.

**Comment by henkelmax** [comment]
You can add other ores with a datapack. For more information look [here](https://github.com/henkelmax/advanced-mining-dimension/tree/master/datapacks).

**Comment by Knito58** [comment]
Thanks, will try this.

**Comment by henkelmax** [comment]
If the ores should spawn by default in this dimension, this might be an oversight by the Gobber devs.

**Comment by Knito58** [comment]
Thanks, maybe I shall report this to the Gobber devs. Maybe not. We'll see. Atm I'm totally fine with your AMD mod.
