### ISSUE TITLE
Crash at Startup (1.16.5)

### ISSUE THREAD

**Issue by Cynix32** [henkelmax/advanced-mining-dimension#31]
Minecraft crashes with the mod installed. I do not have a lot of time right now to isolate if this was caused by an interaction with another mod. Just enough that when turning off this mod, it does not crash.

Using java 8, MC 1.16.4, Forge 36.0.4
Mod jar was "mining_dimension-1.16.5-1.0.1.jar"

Note that I am running Performant, if that helps diagnosing the problem.
it does not generate a crashlog, but here is what i can access from the console (https://controlc.com/c346a1a8). Another note I should add is that this startup crash does not occur when using Forge 36.0.1

**Comment by henkelmax** [comment]
Please use the provided bug template.
This also may be an issue of performant.
