### ISSUE TITLE
1.16.5 crash on startup no performant installed

### ISSUE THREAD

**Issue by christomite** [henkelmax/advanced-mining-dimension#32]
**Please read the [FAQ](https://modrepo.de/minecraft/mining_dimension/faq) before submitting a bug report!**

hard crash on startup

updated to newest version now crash on startup

[debug.log](https://github.com/henkelmax/advanced-mining-dimension/files/5876436/debug.log)

specifically this line...[26Jan2021 16:04:51.213] [main/FATAL] [mixin/]: Mixin apply failed assets/mining_dimension/mining_dimension.mixins.json:MinecraftMixin -> net.minecraft.client.Minecraft: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @ModifyVariable annotation on setFlag could not find any targets matching 'Lnet/minecraft/client/Minecraft;func_238195_a_(Ljava/lang/String;Lnet/minecraft/util/registry/DynamicRegistries$Impl;Ljava/util/function/Function;Lcom/mojang/datafixers/util/Function4;ZLnet/minecraft/client/Minecraft$WorldSelectionType;)V' in net.minecraft.client.Minecraft. Using refmap mining_dimension.refmap.json [PREINJECT Applicator Phase -> assets/mining_dimension/mining_dimension.mixins.json:MinecraftMixin -> Prepare Injections ->  -> localvar$bgp000$setFlag(Z)Z -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyVariable annotation on setFlag could not find any targets matching 'Lnet/minecraft/client/Minecraft;func_238195_a_(Ljava/lang/String;Lnet/minecraft/util/registry/DynamicRegistries$Impl;Ljava/util/function/Function;Lcom/mojang/datafixers/util/Function4;ZLnet/minecraft/client/Minecraft$WorldSelectionType;)V' in net.minecraft.client.Minecraft. Using refmap mining_dimension.refmap.json [PREINJECT Applicator Phase -> assets/mining_dimension/mining_dimension.mixins.json:MinecraftMixin -> Prepare Injections ->  -> localvar$bgp000$setFlag(Z)Z -> Parse]

1.16.5
36.0.4
1.0.1

i have 280 other mods when i remove yours its fine

**Comment by EnterFor** [comment]
Exactly the same question
It seems to have happened after updating Forge...
I'm also using version 36.0.4

**Comment by henkelmax** [comment]
Let me know it it works for you.
