### ISSUE TITLE
can't get datapack working on server (+custom datapack)

### ISSUE THREAD

**Issue by Nyatsuru** [henkelmax/advanced-mining-dimension#33]
Hello,
I wanted to customize the Mining Dimension by adding a datapack, but it didn't change anything other than creating the issue, where right clicking the block doesn't do anything anymore (fixed it tho)

But I still can't get the datapack to work (even in singleplayer)

How I tried it in singleplayer:
1. Creating a new world (level type: Biomes O' Plenty, but also didn't worked on superflat)
also adding datapack
2. enabling datapack with /datapack enable file/(ex.)no_lakes
3. going into the dimension

extra:
I also wanted to make a datapack where there are no caves, canyons, mobs, lakes (lava and water), spawners, mineshafts.
https://pastebin.com/X1tSrPSa
I don't know if I did it right though...

(btw I am new to GitHub, sorry if the submission is wrong...)
Thanks for the help in advance btw! <3

**Comment by henkelmax** [comment]
Have you tried a datapack from the examples?

**Comment by Nyatsuru** [comment]
Yes I tried no_lakes in singleplayer but it didn't work

**Comment by henkelmax** [comment]
Please send me your logs.

**Comment by Nyatsuru** [comment]
[latest.log](https://github.com/henkelmax/advanced-mining-dimension/files/5883715/latest.log)
(singleplayer, tested no lava, didn't work)

[latest.log](https://github.com/henkelmax/advanced-mining-dimension/files/5883724/latest.log)
(multiplayer world, tested last with custom datapack (but also didn't work with presets)

**Comment by henkelmax** [comment]
This has nothing to do with the datapack.

> [00:14:14] [Render thread/INFO]: [CHAT] The Mining Dimension hasn't been created yet. This is a [BUG]. 
[00:14:14] [Render thread/INFO]: [CHAT] A workaround can be found [HERE].

This message indicates [this](https://bugs.mojang.com/browse/MC-195468)
A workaround can be found [here](https://github.com/henkelmax/advanced-mining-dimension/issues/14#issuecomment-707924771)

**Comment by Nyatsuru** [comment]
Yes I already used that workaround but it still not fixes the problem, that the datapack isn't working
Video of me creating a new world and inserting the datapack:

https://www.youtube.com/watch?v=nfYBHYyFi7c&feature=youtu.be

**Comment by henkelmax** [comment]
You didn't activate the datapack. You have to press on the arrow to put in in the right column.

**Comment by Nyatsuru** [comment]
That's embarassing... I am soo sorry to waste your time... (never used datapacks before)
I just tested it and it worked with the "no_lava" preset.

When I use that custom one, the dimension does not generate... I'll look into it and write an update here (if that's ok)
Thank you for your time...
Have a nice day!

**Comment by Nyatsuru** [comment]
I did it!
The custom datapack works (no caves/lava/canyons etc.) and ores from other mods spawn too!
If anyone wants to use this, here you go:
[just_mine.zip](https://github.com/henkelmax/advanced-mining-dimension/files/5887935/just_mine.zip)

Now that I know how to use that datapack, I'll write a little tutorial
How to use it and how to get it into an existing world:

**1. Create a new world**
2. Click on "Data Packs"
3. "Open Pack Folder" and paste the datapack into the folder (idk if you need to unzip it but better just do it).
Make sure you press the arrow on the datapack to put it into the right ("Selected") Column! (thx henkelmax <3)
Click "Done"
4. Create the new world
_(idk if the next steps are necessary)_
5. Place the Mining Dimension Block and go into the world to check if it worked
6. Save and exit the world

**Export it into existing world:**
1. insert the datapack into the world
2. replace the current "dimensions" folder with the one you created in step 1-6
3. done, you should have the mining dimension with the right config

(also works on servers)
(btw, only use one datapack preset for the mining dimension...)

**Comment by henkelmax** [comment]
Thank you for sharing your work! I'm glad that it worked.
