### ISSUE TITLE
is there a way to get the datapacks to work with a world already created?

### ISSUE THREAD

**Issue by DragonKing810** [henkelmax/advanced-mining-dimension#34]
i would rather not have to restart my whole world over just to do this that would be a big pain x.x

**Comment by henkelmax** [comment]
I think if you add a datapack afterwards, new generated chunks should be working.

**Comment by DragonKing810** [comment]
> I think if you add a datapack afterwards, new generated chunks should be working.

doesnt seem to work cause i put no mobs and mobs are still spawning in the dimension.

**Comment by henkelmax** [comment]
Please send me your logs.

**Comment by JackoDEJ** [comment]
Has there been any more development on this issue? I am having the same issue.

**Comment by henkelmax** [comment]
Since I got no logs, I couldn't reproduce the issue.
You can send me your logs if you are facing the same issue.

**Comment by DragonKing810** [comment]
sry it seems to be a bug on my end i had to make a whole new world and it
worked
