### ISSUE TITLE
[Config Option Request] Day/Night Cycle + Bed-Allowed Toggle

### ISSUE THREAD

**Issue by GalacticRuler** [henkelmax/advanced-mining-dimension#35]
I'd just like to be able to toggle sleeping/bed on for the mining dimension, and allow time to pass there with a day/night cycle. this would help balance things a bit (since it seems mods consider it permanent day there) and allow things like Minecolonies to work right

**Comment by henkelmax** [comment]
You can change every aspect of the dimension with a datapack.
