### ISSUE TITLE
[1.16.4] Voxelmap + AMD teleporter = Crash

### ISSUE THREAD

**Issue by GalacticRuler** [henkelmax/advanced-mining-dimension#36]
**Please read the [FAQ](https://modrepo.de/minecraft/mining_dimension/faq) before submitting a bug report!**

**Bug description**
Using Voxelmap and using a teleporter to the mining dimension crashes the client

**Steps to reproduce the issue**
1. have both mods installed
2. Craft and place a mining dimension TP block
3. use it
4. repeat until crash. Partially inconsistent

**Log files**
Logs are long since gone but can be generated soon after this is posted. Will attach in reply

**Versions**
- MC 1.16.4
- Forge 3.1.4
- mod 1.0.2

mod is running on a dedicated server, updating said server would be....troublesome. Issue is 100% avoidable if any other form of teleporter is used to enter the dimension. It is *only* the included block that causes it. It also doesn't occur with other minimaps, that I've tested.

**Comment by henkelmax** [comment]
I had the same bug about a year ago. I'm pretty sure this is a bug of VoxelMap. Please report it to their issue tracker.

**Comment by GalacticRuler** [comment]
that would make sense

whenever I can get a log file, I will
