### ISSUE TITLE
Spawning modded ores exclusively in mining dimension

### ISSUE THREAD

**Issue by BobiderBob** [henkelmax/advanced-mining-dimension#39]
Hello

my brother and I have been working on a modpack and have been enjoying your mod so far.
Is there any way to make ores (for example bauxite from immersive engineering) spawn exclusively in your mining dimension?

For balancing reasons we have disabled some ores (for example Mekanism Ores) from spawning in general. But this of course leads to not being able to mine theses at all and they need to be added to a mining dimension.

We have tried to add .json definitions for ores and include them in the mining.json file. Unfortunately, the server always spits out an unknown JSON object error, and we never got a mining dimension working with a datapack, that was not a direct copy of an example. Even adding vanilla blocks like clay as ores never worked for us.

Also, we never figured out, where these predefined minecraft:ore_xyz are located/defined to take a look at them.

This [datapack](https://github.com/henkelmax/advanced-mining-dimension/files/6076194/modded_ores.zip) is what we came up with so far.

Would greatly appreciate your help since we are kinda new to dimensions in datapacks :D

Best Regards
Kaliber Bros

**Comment by henkelmax** [comment]
You are clearly doing it wrong. You have to add the ore definition to configured_feature.
This name has to be exactly referenced in the mining.json in the biome folder.
For you that would be:
``` json
"features": [
    [
      "minecraft:ore_dirt",
      "minecraft:ore_gravel",
      "minecraft:ore_granite",
      "minecraft:ore_diorite",
      "minecraft:ore_andesite",
      "minecraft:ore_coal",
      "minecraft:ore_iron",
      "minecraft:ore_gold",
      "minecraft:ore_redstone",
      "minecraft:ore_diamond",
      "minecraft:ore_lapis",
      "minecraft:ore_emerald",
      "mining_dimension:immersiveengineering"
    ]
  ],
```

Your immersiveengineering.json also seems to be wrong. You can just copy an ore from the example datapacks:
https://github.com/henkelmax/advanced-mining-dimension/blob/master/datapacks/more_ores/data/mining_dimension/worldgen/configured_feature/ore_iron.json

**Comment by BobiderBob** [comment]
Hello

thanks for the quick response.
Unfortunately, I still can't get it working.

I did, what you told me above, but I think the feature files are still wrong.
(I am a bit confused by all the elements in this json file.)
It now looks like this: [mining_dimension.zip](https://github.com/henkelmax/advanced-mining-dimension/files/6077341/mining_dimension.zip)

By the way, the error message looks like this:
[17:07:26] [main/ERROR] [minecraft/BiomeGenerationSettings]: Feature: Not a JSON object: "mining_dimension:mekanism_uranium"; Not a JSON object: "mining_dimension:mekanism_tin"; Not a JSON object: "mining_dimension:mekanism_osmium"; Not a JSON object: "mining_dimension:mekanism_fluorite"; Not a JSON object: "minecraft:ore_emerald"; Not a JSON object: "minecraft:ore_lapis"; Not a JSON object: "minecraft:ore_diamond"; Not a JSON object: "minecraft:ore_redstone"; Not a JSON object: "minecraft:ore_gold"; Not a JSON object: "minecraft:ore_iron"; Not a JSON object: "minecraft:ore_coal"; Not a JSON object: "minecraft:ore_andesite"; Not a JSON object: "minecraft:ore_diorite"; Not a JSON object: "minecraft:ore_granite"; Not a JSON object: "minecraft:ore_gravel"; Not a JSON object: "minecraft:ore_dirt"

Thanks for your help
Kaliber Bros

**Comment by henkelmax** [comment]
I don't know what exactly the problem is, but my approach would be to take the example datapack and only make very minor changes and always check if it works.

**Comment by undercoverturbo** [comment]
Thanks for your help.
We got it working now, by doing exactly what you said.
Taking an example and doing minor changes to it.
And trying that over and over again :)

**Comment by henkelmax** [comment]
Great!
