### ISSUE TITLE
Feature Request: Config option to spawn players on the highest valid block rather than the lowest.

### ISSUE THREAD

**Issue by Weedoof** [henkelmax/advanced-mining-dimension#42]
As the title.

An optional config to allow players to spawn on the highest valid block would be appreciated. That way, if someone uses a data pack to add a surface to the world, they'd spawn on that rather than deep underground.

I don't deny that this might be more effort than its worth, given that the only change by default would be spawning players in higher up caves, or depending on their luck, in a water pool far above anything. But I'd certainly appreciate it, and I'm sure others would too.

**Comment by Winddbourne** [comment]
I'd actually prefer the closest valid block, or the exact same location if possible. This is a dimension of caves from top to bottom. If I enter it from the top of a mountain why shouldn't I enter a cave higher up in the world? If I do so from bedrock then there still should be a cave somewhere close to that . . .
