### ISSUE TITLE
Random spawn from regular Dirt / Sand / Normal ground

### ISSUE THREAD

**Issue by alfonsan** [henkelmax/advanced-mining-dimension#44]
**Is your feature request related to a problem? Please describe.**
Yes, the problem of wasting too much time cleaning regular ground. As well as with the regular rock, this mod brings some "fun" or "gratification" when you have to invest time on those, so why not include the regular ground with small chances of dropping related items?

**Describe the solution you'd like**
When you clean regular ground, you have a chance of drops.

**Describe alternatives you've considered**
First alternative would be seeds and normal items that would be overland. Second would be with an even smaller percentage to have minerals drop.

**Additional context**
Nope, its an easy concept. Give a little bit of fun and reward to the long days of terrain removal.

**Comment by henkelmax** [comment]
This is not the purpose of the mod. It is just a dimension with the same cave system of the overworld.

**Comment by alfonsan** [comment]
Sorry, I missed the github page lol. I got several tabs openned at the same time. Could you please delete this?
