### ISSUE TITLE
Crash whenever using datapacks (confirmed More caves No lava)

### ISSUE THREAD

**Issue by ImPickleJeff** [henkelmax/advanced-mining-dimension#45]
**Bug description**
Downloaded and installed the More caves No lava, More ores, and No mobs datapacks as instructed, whenever I went into the dimension my game crashed, causing me to be unable to access my world. May also be an issue with other datapacks. 
When I used only More caves No lava, still crashed on my second visit (first was me hopping in then hopping out). It also had lava in the dimension by my spawn, so the datapack didn't work.

**Steps to reproduce the issue**
1. Install the datapacks
2. Create new world and add datapacks
3. Go to dimension
4. Crash, receive error code 0, and be unable to retrieve world

**Expected behavior**
Expected dimension to have more caves, no lava, more ores, and no mobs. Also didn't expect to crash.

**Log files**
Should be the crash log for ONLY 'More caves No lava'
https://ufile.io/39x24ytu

**Versions**
- 1.16.5
- 36.1.0
- 1.0.3

**Other mods**
Abnormals core
Ars Nouveau
Artifacts
Bookshelf
Buzzier Bees
Citadel
Construction wand
Cucumber
Curios forge
Druidcraft
Easy Piglins
Easy Villagers
Eidolon
Enchantment Descriptions
Endergetic
Fast Leaf Decay
Gecko lib
Guard Villagers
Ice and Fire
Iron Chest
Jei
Lollipop
Lost Trinkets
Mowzies Mobs
Mystical Aggradditions
Mystical Agriculture
Neat
OptiFine
Patchouli
Reliquary
Savage and Ravage
Save my stronghold
The Undergarden
Upgrade Aquatic
Valhelsia Structures
Waystones
Wyrmroost
Xaeros World Map

EDIT: It doesn't work with just the one datapack, I did say but it's okay if it wasn't clear.
Not sure if it works without other mods, I uninstalled the mod so I can't say.

**Comment by henkelmax** [comment]
I need your logs.
Does it work with no other mods installed?
Does it work with just a single datapack?

**Comment by ImPickleJeff** [comment]
> I need your logs.
> Does it work with no other mods installed?
> Does it work with just a single datapack?

Added logs, edited post.

**Comment by henkelmax** [comment]
The problem seems to be Mowzie's Mobs.
Can you remove that mod and try it again?

**Comment by henkelmax** [comment]
Found the issue: https://github.com/BobMowzie/MowziesMobs/issues/331
Please update Mowzie's Mobs
