### ISSUE TITLE
Portal not working on server (FIX ISNT WORKING!)

### ISSUE THREAD

**Issue by AirplanegoBrr** [henkelmax/advanced-mining-dimension#46]
Im not sure what to do!
I did this https://github.com/henkelmax/advanced-mining-dimension/issues/14#issuecomment-707924771 and it doesnt work!!! Im not sure what to do! Does someone have any ideas on what I should do?? Please DM me or something for logs as I don't know where all the IP's for me and my friends are and dont wanna look so just DM me on discord !!AirplaneGoBrr!!#1613

(Also this mod should have a support discord)

**Comment by henkelmax** [comment]
Please fill out the complete bug tamplate.

**Comment by AirplanegoBrr** [comment]
**Bug description**
Mining dim not working

**Steps to reproduce the issue**
1. Go into MP world and try to use the mining dim and get this error https://user-images.githubusercontent.com/71111395/114333362-f9e67c00-9afc-11eb-9c0a-1489409aecb3.png
2. try to fix it by starting a single-player world and go into the portal then drag the dimensions folder from the single-player world to the world folder in the server
3. Restart the server
4. Same error

**Expected behavior**
Go to the mining dimension and find ores 

**Log files**
Please DM me on discord as player IPs are in the logs! !!AirplaneGoBrr!!#1613

**Versions**
- Minecraft version 1.16.5
- Forge version 36.1.4
- Mod version 1.16.5-1.0.3

**Other mods**
Mod list: https://drive.google.com/file/d/1bQ89mRbQQeiY1ms9XN-0xpk75rYJSP_2/view?usp=sharing

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by AirplanegoBrr** [comment]
**Bug description**
Mining dim not working

**Steps to reproduce the issue**
1. Go into MP world and try to use the mining dim and get this error https://user-images.githubusercontent.com/71111395/114333362-f9e67c00-9afc-11eb-9c0a-1489409aecb3.png
2. try to fix it by starting a single-player world and go into the portal then drag the dimensions folder from the single-player world to the world folder in the server
3. Restart the server
4. Same error

**Expected behavior**
Go to the mining dimension and find ores 

**Log files**
Please DM me on discord as player IPs are in the logs! !!AirplaneGoBrr!!#1613

**Versions**
- Minecraft version 1.16.5
- Forge version 36.1.4
- Mod version 1.16.5-1.0.3

**Other mods**
Mod list: https://drive.google.com/file/d/1bQ89mRbQQeiY1ms9XN-0xpk75rYJSP_2/view?usp=sharing

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Have you tried it with just the mining dimension mod installed and no datapacks?

**Comment by AirplanegoBrr** [comment]
Works on server with just the mining dim mod

**Comment by henkelmax** [comment]
Then just add your mods one by one and test if it works. Let me know what mod is causing it and I will look into that.

**Comment by AirplanegoBrr** [comment]
That's a joke right?

**Comment by henkelmax** [comment]
I can't magically find out which of your mod is causing it.

You can find the mod in question in a few steps.
1. Remove half of the mods and check if it works
2. If yes, take the other half
3. If no, half it again
Just repeat that until you only got one.

**Comment by AirplanegoBrr** [comment]
Do you think me sending the logs to you will help at all?

**Comment by henkelmax** [comment]
Maybe, but since you didn't sent them I guess there were no errors.

**Comment by AirplanegoBrr** [comment]
https://pastebin.com/WdqVyuZj here is logs
![image](https://user-images.githubusercontent.com/71111395/114944597-c2c5e280-9dfc-11eb-97df-3775657212fc.png)
+picture

**Comment by henkelmax** [comment]
Can't find anything about the mining dimension in the logs. But some of your mods seem to cause a lot of exceptions. (I would recommend you to look into that!)


You have to find out which mod causes the mining dimension to break.

**Comment by henkelmax** [comment]
Closed due to inactivity
