### ISSUE TITLE
Teleporter duplicating itself

### ISSUE THREAD

**Issue by Zerahn** [henkelmax/advanced-mining-dimension#47]
I'm playing Garden of Glass, or this wouldn't be much of an issue (because the duplicate portal would be buried underground somewhere, but with GoG it's completely visible). I've placed a mining portal at overworld:256 62 255 which leads to mining_dimension:256 12 245. I'm not sure when it happens, probably when returning to the overworld, but despite being taken back to overworld:256 62 255, a duplicate mining dimension portal is created at overworld:256 12 245. Every time I break it, it comes back. I reported this ages ago and I think back then I manually placed a portal in the mining dimension at the same coordinates as the one in the overworld and it stopped duplicating it - or maybe it just placed it in the same spot there already was one.

I noted in MiningDimensionTeleporter.java there's a findPortalInChunk check, and if it returns null it places a teleporter. The placeTeleporter functions accept a World argument, but the findPortal function does not. Could that be causing the check to return null when it shouldn't?

**Comment by henkelmax** [comment]
Please fill out the complete bug template.

**Comment by henkelmax** [comment]
Nevermind. I know what the issue is.
This is a very old minecraft bug.
If you right click a block just before you teleport to another dimension, this block will appear at these coordinates in the other dimension.
This block isn't actually there this is just a ghost block.
