### ISSUE TITLE
Can't excavate vanilla stones in Forge Server.

### ISSUE THREAD

**Issue by Theoretical-Enday** [henkelmax/advanced-mining-dimension#49]
[mod list.txt](https://github.com/henkelmax/advanced-mining-dimension/files/6445972/mod.list.txt)
![QQ截图20210508195155](https://user-images.githubusercontent.com/73912246/117542495-d529e980-b053-11eb-9c40-859e197c3251.png)
I use 1.16.5 / 36.1.16 Forge and a Forge server
I added this mod to my server, then i go in mining dimension.
But i can't excavate vanilla stones(all) in survival mode(vanilla tools,silentgear,Mekanism's atomic_disassembler and Empty-handed), like Unbreakable(no % action in screenshot )in this dimension.
Mods stones and ores can  excavate, Mekanism's digital_miner also works fine
I test in a single save can do normal

**Comment by henkelmax** [comment]
Does this happen without any other mods installed?

**Comment by Theoretical-Enday** [comment]
no,I only tested it with 1 mod alone, and no unbreakable situation occurred.

**Comment by Theoretical-Enday** [comment]
Dirt,Gravel,Clay,Cobblestone and ores can excavate,mod's marble and ores can excavate,only the vanilla stones can't

**Comment by henkelmax** [comment]
Then please check which mod causes this.

**Comment by Theoretical-Enday** [comment]
It's another mod's problem. I'm very sorry to disturb you, thanks your good mods!
