### ISSUE TITLE
[Suggestion] Nether mining dimension

### ISSUE THREAD

**Issue by DeckerExpert** [henkelmax/advanced-mining-dimension#50]
**Describe the feature you'd like**
I have an idea where there is a nether version of the mining dimension. It could be a second teleporter block that only teleports you to the nether or placing the main teleporter block in the nether and it will teleport you there. It should have all the ores present in the nether. (i.e. quartz, nether gold ore, ancient debris, etc.) 

**Describe alternatives you've considered**
There are 3 alternatives I have considered for transportation into the nether version of the mining dimension. They are:
- Placing a teleporter block in the nether, right clicking it, and it will teleport you into the nether mining dimension.
- Have some sort of GUI that asks you if you want to go to the overworld-type mining dimension or a nether-type mining dimension.
- Having a second type of teleporter block that will only teleport you to the nether mining dimension.

**Additional context**
The generation of the nether version mining dimension could be just the same with the current generation for the overworld-type mining dimension, except for more lava lakes, stone to be replaced with netherrack, and the generation of nether ores.

**Comment by henkelmax** [comment]
This mod will always only have 1 mining dimension. If you want, you can change the world type of the dimension to nether.
