### ISSUE TITLE
Can a unique seed be used for creating the mining dimension?

### ISSUE THREAD

**Issue by Paladin62** [henkelmax/advanced-mining-dimension#51]
I would like to create a new mining dimension for my Forge server.  Perhaps resetting the dimension weekly or monthly.  I understand that if I delete the \dimensions\mining_dimension folder the dimension will be recreated, but I would like to be able use a new seed each time.

I have tried using the example default data pack which has the following, but changing the seed does not seem to change the generation.
`{
  "generator": {
    "type": "minecraft:noise",
    "biome_source": {
      "type": "minecraft:fixed",
      "biome": "mining_dimension:mining"
    },
    "seed": 0,
    "settings": "mining_dimension:mining"
  },
  "type": "mining_dimension:mining"
}`

**Comment by henkelmax** [comment]
I don't think this is possible, since it always uses the general world seed.
