### ISSUE TITLE
No caves and monsters

### ISSUE THREAD

**Issue by JoachimTT** [henkelmax/advanced-mining-dimension#52]
I just want to be able to mine undisturbed by monsters and I want to be able to make my own mines, not have big holes in the midst of my strip mining, When I remove caves from the mining file it still spawns holes, and I dont know how to remove all the airpockets.

I just want a data pack that disables caves from generating and monsters from spawning

Alternatives for this would be:
1. Configurable menu inside the game, like it used to
2. Downloadable datapack

**Comment by henkelmax** [comment]
You can do these datapacks on your own. This mod just adds the dimension and the teleporter itself.
The datapacks on GitHub are just examples to see how it works.

**Comment by JoachimTT** [comment]
But how I.. ok
