### ISSUE TITLE
Monsters still spawn when the "no mobs" datapack is on

### ISSUE THREAD

**Issue by JoachimTT** [henkelmax/advanced-mining-dimension#53]
So when I put the no mobs datapack inside my game, and I enter the dimension, monsters still spawn.

1. Download the advanced mining dimension datapack that consists of already made settings/configs
2. I go to make a new world and select the data pack buttton
3. I put in the "no_mobs" datapack file in the datapack folder for my world
4. I join my world and enter the dimension
5. and monsters still spawn

No monsters should spawn whatso ever

- 1.16.5
- 36.1.31
- mining_dimension-1.16.5-1.0.5.jar

**Comment by JoachimTT** [comment]
I couldnt put my mod folder here :|

**Comment by JoachimTT** [comment]
It's a mod compatibility, I dont know how to put a list of my mods here

**Comment by henkelmax** [comment]
You need to activate the datapack. Just putting it into the folder does not work.

**Comment by JoachimTT** [comment]
How I do that??

**Comment by henkelmax** [comment]
Just click on the arrow on the datapack in the datapack screen, so that it is on the right side and not on the left.

**Comment by JoachimTT** [comment]
.. yeah i did that, I tested it out with only that mod and it worked, so its a compatibility issue

**Comment by henkelmax** [comment]
https://github.com/henkelmax/advanced-mining-dimension/issues/25#issuecomment-738673204

**Comment by henkelmax** [comment]
> .. yeah i did that, I tested it out with only that mod and it worked, so its a compatibility issue

Then you need to find out which mod causes it.

**Comment by JoachimTT** [comment]
oh god, oh no

**Comment by JoachimTT** [comment]
do you have a list of mods that are in compatible?

**Comment by JoachimTT** [comment]
I'll figure it out, thanks for all the help and support :)

**Comment by henkelmax** [comment]
> do you have a list of mods that are in compatible?

No

> oh god, oh no

Just take half of the mods and see if it still occurs, if not, take the other half, repeat this until only one mod is left.

**Comment by henkelmax** [comment]
It would also help if you post your logs (Please use GitHub gist)

**Comment by JoachimTT** [comment]
How do I post gist?

**Comment by JoachimTT** [comment]
`<script src="https://gist.github.com/JoachimTT/a53298377aeae1bd985f67d1f6f0c03b.js"></script>`

**Comment by JoachimTT** [comment]
https://gist.github.com/JoachimTT/a53298377aeae1bd985f67d1f6f0c03b

**Comment by henkelmax** [comment]
> https://gist.github.com/JoachimTT/a53298377aeae1bd985f67d1f6f0c03b

So there's nothing obvious in your logs, so you need to find out which mod is causing it.

**Comment by JoachimTT** [comment]
What kind of mod could affect this? world generation mods or..?

**Comment by henkelmax** [comment]
> Just take half of the mods and see if it still occurs, if not, take the other half, repeat this until only one mod is left.

This is the fastest approach.

**Comment by JoachimTT** [comment]
yes, but still do you know what kind of mods could cause this??

**Comment by henkelmax** [comment]
No clue... Most obvious would be mods that alter world generation or add custom ores.

**Comment by JoachimTT** [comment]
I got a few of those, that could make sense

**Comment by JoachimTT** [comment]
I found the problem
Caves & Cliffs Backport by blackgear27

I disabled that mod and now no monsters spawn except those found in spawners

**Comment by JoachimTT** [comment]
thanks for your help :D
