### ISSUE TITLE
[Feature Request] Extra Cave Biome Types

### ISSUE THREAD

**Issue by Winddbourne** [henkelmax/advanced-mining-dimension#54]
**Is your feature request related to a problem? Please describe.**
Right now the mining dimension has only one biome, and that's great. But it does mean that you don't get variety when you try to pair it with something like Subterranean wilderness, Quark, or Geolyses which provide cave enhancements related to surface biome type. 

**Describe the solution you'd like**
The simplest solution would be just to copy the biome you already have and change the base biome type. Of course building on this you could

**Describe alternatives you've considered**

For now I'm going to set quark to only spawn it's cave Biomes in this dimension and thus also in your single biome while keeping the more advanced ore types and more varied cave Biomes in the Overworld. It's not perfect, but it will work. 

I also considered making my own mining dimension using data packs and immersive portals. But that would be a lot of extra work for just one mod pack, and I haven't really found a good solution for immersive portals always sticking me on the roof of my cave dimension anyway. I'm sure I could figure it out but . . . all that effort wouldn't give ME increased inter mod compatibility or a base to build more cool stuff on the way it would for you. :)

**Comment by henkelmax** [comment]
Everything you want to do can be done with datapacks.
The main feature of this mod is actually the teleporter.
The dimension itself is just a datapack.
