### ISSUE TITLE
Support for Thermal Foundation

### ISSUE THREAD

**Issue by judicius** [henkelmax/advanced-mining-dimension#55]
**Is your feature request related to a problem? Please describe.**
I'm just looking for Thermal Foundation ores to be supported in the mining dimension.

**Describe the solution you'd like**
I'd like to seem them supported natively but if not, I'd like to know how to add them via datapack. Detailed instructions or specific examples greatly appreciated.

**Describe alternatives you've considered**
I've attempted to add them copying syntax from your datapack examples but haven't been able to get them to generate at all.

**Additional context**
Perhaps the simplest solution would be an example of how to add a modded ore via the datapack tutorial.

**Comment by henkelmax** [comment]
Just take the more ores datapack as an example.
There are also plenty tutorials on how to make a datapack online.
