### ISSUE TITLE
New Dimension configuration

### ISSUE THREAD

**Issue by TheEmporerYT** [henkelmax/advanced-mining-dimension#57]
Would it be possible to have a new configuration that has HALF of all the ores within the dimension? Simply put, I am wanting to eventually make a series on YT of a modpack that I made going from basically nothing on a skyblock world to a fully autonomous flying island through the create mod. So, to add a bit of difficulty, I wanted to make the mining dimension to have half of all the available ores.

**Comment by henkelmax** [comment]
There are plenty of example datapacks. You can just tweak the values.
