### ISSUE TITLE
astral sorcery compatibilty

### ISSUE THREAD

**Issue by mrpotato06** [henkelmax/advanced-mining-dimension#58]
please add in the mining dimension the ores from astral sorcery (rock crystal,aquamarine) aka astral sorcery compatiblity

**Comment by henkelmax** [comment]
You can just add them with a datapack. See [datapacks](https://github.com/henkelmax/advanced-mining-dimension/tree/master/datapacks).

**Comment by mrpotato06** [comment]
> You can just add them with a datapack. See [datapacks](https://github.com/henkelmax/advanced-mining-dimension/tree/master/datapacks).

how, i dont see a datapck with astral ores

**Comment by henkelmax** [comment]
These are just example datapacks for reference.

**Comment by mrpotato06** [comment]
> These are just example datapacks for reference.

ah ok thanks, have a nice day
