### ISSUE TITLE
[Question] Configure Mine Dimensions for surface world.

### ISSUE THREAD

**Issue by adamhoheisel** [henkelmax/advanced-mining-dimension#61]
Hello,

I would like to configure my mining dimension to have a surface instead of just caves for the use of mining equipment from other mods. How can I go about doing this? Can this be accomplished via the data packs? 

Also is there any API or syntax reference documentation for the data packs? 

Thanks in Advance!

**Comment by henkelmax** [comment]
The dimension is just a datapack. So every cistom dimension works.
