### ISSUE TITLE
Caves and Cliffs Datapack Compatibility (1.16.5)

### ISSUE THREAD

**Issue by InfinitysDaughter** [henkelmax/advanced-mining-dimension#62]
(Forgive me but this isn't actually a bug report. Its a way to fix the problem I've seen a number of people have had.)

Note: This is for the Caves and Cliffs backport by blackgear27 that requires their CaveBiomeAPI. I dont know if it will work with other backports because this seems to be the only one using this kind of cave biome setup but they have the most complete 1.17 backport mod and I know many people use it.

_**Fix:
Open your config folder and open the cavebiomeapi-common file in a text editor. Edit the line ["Generate Default Cave Biome" = true] to read ["Generate Default Cave Biome" = false].**_

As the file says, this wont disable the 1.17 lush caves generation so dont worry about missing out on that. This will let the mining dimension recognize the datapacks you want to use so you can still have your axolotls and a dedicated mining dim!

**Comment by henkelmax** [comment]
Why did you report this as a bug if you have a fix for it?

**Comment by InfinitysDaughter** [comment]
"Its a way to fix the problem **_I've seen a number of people have had_**"

Because I've seen a number of people with the same problem and the only solution I've seen posted was just "remove C&C backport" which I didn't want to do. I thought it would be helpful for other people and I thought you may like to know about it, too, so you could advise others better.

**Comment by henkelmax** [comment]
Oh, sorry I misunderstood.
