### ISSUE TITLE
Unable to add new structures to dimension, unable to change stone to modded block

### ISSUE THREAD

**Issue by RobertHDPotatoes** [henkelmax/advanced-mining-dimension#63]
**Bug description**
When I try to change the default block of the Mining Dimension to "cavesandcliffs:deepslate" instead of stone, if I try to enter the mining dimension I get the error message "The Mining Dimension hasn't been created yet. This is a bug. A workaround can be found here". Firstly, I am on a single player world that has never been multiplayer, if I create a new single player world I get the same issue. Secondly, I have replaced the default block with cobblestone and Quark's slate instead of stone before, so I know that I am doing it right, it just seems like the modpack will not accept some modded blocks.

 I also get the same problem when trying to add structures to the structures list. Also, fossils don't generate normally when they should be as listed in mining_dimension\worldgen\noise_settings\mining.json (At least I am pretty sure they are supposed to generate. But none generate for me.)

If I am doing something wrong please tell me, I am honestly having a hard time understanding the datapack files but I do think this is a bug.

**Steps to reproduce the issue**
This is the easiest way to reproduce the issue:
1: Install Quark (or Caves And Cliffs Backport)
2: Change all "minecraft:stone" entries to certain modded blocks such as "cavesandcliffs:deepslate" or "quark:deepslate" in the file mining_dimension\worldgen\configured_surface_builder\mining.json
3: Change the "default" block to the same modded block as before, such as "cavesandcliffs:deeplsate" in the file mining_dimension\worldgen\noise_settings\mining.json
4: Load up a single player world with your added datapack that has those changes, and try to enter the mining dimension, you get the error in chat.

**Expected behavior**
I expect that if I change the default block to "quark:deepslate" or "cavesandcliffs:deepslate", that it will replace all stone in the mining dimension with deepslate. I have successfully replaced the default stone blocks with cobblestone blocks doing this method, but using modded blocks gives an error in chat for something seemingly unrelated.

**Log files**
Latest log: https://pastebin.com/Wq6z3Msm

**Versions**
- Minecraft version: 1.16.5
- Forge version:  36.2.20
- Mod version: 1.0.6

**Other mods**
After that log file that I posted, I tested it with literally only:
Quark, AutoRegLib, & Advanced Mining Dimension
And I still got the issue.

Also could I get an example on how to add more structures? If I try to add more structures, I get the same problems as I've just listed above. I've just been trying to add them to the list right below where the fossil structure is. Do they need to be added in another place as well?

**Comment by henkelmax** [comment]
This is not a bug with the mod. This only happens of you have an error in your datapack.
There are plenty tutorials for custom world datapacks on the internet.

**Comment by RobertHDPotatoes** [comment]
After a few more hours of troubleshooting, I realized you are correct. I didn't notice that the specific block I was trying to use (quarks deepslate or cavesandcliffs deepslate) are both directional blocks, and requires an axis property to properly generate (Whoops). Thanks.

**Comment by RobertHDPotatoes** [comment]
Just in case anyone else runs into this issue, here's a link to my working script (in file location openloader\data\Mining Dimension\data\mining_dimension\worldgen\configured_surface_builder): https://pastebin.com/BST0Bq5s
