### ISSUE TITLE
How can i generate Certus quartz ore from AE2

### ISSUE THREAD

**Issue by chouuul** [henkelmax/advanced-mining-dimension#65]
**Please read the [FAQ](https://modrepo.de/minecraft/mining_dimension/faq) before submitting a bug report!**

**Bug description**
I want to know how to generate Certus quartz ore from AE2 in mining dimension.

**Steps to reproduce the issue**
Create a mining world with AE2 installed.
See

**Expected behavior**
There is no Certus Quartz Ore in mining dimension. 
How can I generate it ? I don't know how to dev a datapack

**Log files**

**Versions**
- Minecraft version 1.16.5
- Forge version 36.2.20
- Mod version 1.0.6

**Other mods**
Applied energistics 2

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
You can create a datapack to add these ores. See the datapack examples for reference datapacks.
