### ISSUE TITLE
Mining Dimension Farming Bug

### ISSUE THREAD

**Issue by Plasmanaut2** [henkelmax/advanced-mining-dimension#66]
**Bug description**
The Industrial Foregoing Plant Gatherer does not harvest Mystical Agriculture plants in the Mining Dimension

**Steps to reproduce the issue**
1. Go to mining dimension
2. Plant Mystical Agriculture seeds
3. Let it grow to maturity
4. Place Industrial Foregoing Plant Gatherer
5. Power it, by battery or connected energy block, if needed, use range upgrades to reach the Mystical Agriculture plant

**Expected behavior**
Industrial Foregoing Plant Gatherer should harvest Mystical Agriculture plants in the mining dimension as it does correctly in the overworld.

**Versions**
- Minecraft 1.18.2
- Forge 40.1.48
- 1.70-build.25+mc1.18.2

**Other mods**
TNP Limitless 5 modpack

**Comment by henkelmax** [comment]
This mod isn't even out for 1.18
