### ISSUE TITLE
Data Packs

### ISSUE THREAD

**Issue by AkitaAttribute** [henkelmax/advanced-mining-dimension#70]
**Is your feature request related to a problem? Please describe.**

More information surrounding data pack configuration expected by this mod.

**Describe the solution you'd like**

An updated ReadMe file.

**Describe alternatives you've considered**

I've done some research on finding alternative solutions, but your mod seems to be an adequate band-aid for my reluctance to learning creating my own custom dimensions.  

**Additional context**

Your mod is already great, but I'm hoping to get some more information in terms of modifying the Data Packs for use on servers.  Your explanation involves using the Minecraft UI, which takes me to an appdata location.  This doesn't exist on Linux, so I'm hoping for more direct information about where these configurations end up.  [This information](https://minecraft.fandom.com/wiki/Custom_dimension) suggests that I can place the json into the /world/data/... directory.  I'm not seeing any data in there relevant to your mod currently though.  

Hoping to get some clarification if possible.  Thanks.

**Comment by henkelmax** [comment]
This isn't anything special. It's just a Minecraft datapack. There are plenty of tutorials on how to install or create datapacks for Minecraft.
I won't add any in depth tutorial on how to install them, since this is not a feature of the mod. The mod just adds a teleporter and a template datapack.
