### ISSUE TITLE
[Feature request] Bed Config Option

### ISSUE THREAD

**Issue by Supertacoz** [henkelmax/advanced-mining-dimension#71]
I would like to request the ability to configure whether or not beds can be used within the dimension. 

I am not referring to being able to sleep in the dimension, just being able set it in the config so that there is the option for being able to right click a bed to set spawn instead of it blowing up.

**Comment by henkelmax** [comment]
The dimension is just a datapack. You can change that behavior with your own datapack. This mod just adds the teleporter. The rest can be completely changed with datapacks.

**Comment by Supertacoz** [comment]
I don't know how to make datapacks though. how would I make a datapack to do this?

**Comment by henkelmax** [comment]
There are plenty of resources for this on the internet.
