### ISSUE TITLE
when you go thru the teleporter it sends 2 commands which i cant disable that

### ISSUE THREAD

**Issue by john13210** [henkelmax/advanced-mining-dimension#72]
**Bug description**
If you go thru the portal it sets the weather to clear and time to day

**Expected behavior**
yea i dont want that
- there should be a config file to turn it off and i cant find it
-you should put it in the mining_dimension-server.toml config file i guess

**Log files**
it doesnt matter

**Versions**
- Minecraft version 1.18.2
- Forge version 40.2.5
- Mod version 1.0.0

**Other mods**
SkyT modpack

**Screenshots (Optional)**
![image](https://github.com/henkelmax/advanced-mining-dimension/assets/65425849/91e2d3b0-3e0f-43e8-9afd-beb923cfd6a0)

**Comment by henkelmax** [comment]
Thats not done by the mod. That might be some datapack or other mod you are using.

**Comment by john13210** [comment]
hmm ok
