### ISSUE TITLE
Portal block moves 

### ISSUE THREAD

**Issue by JanneVed** [henkelmax/advanced-mining-dimension#73]
**Bug description**
When going back and forth between dimensions, a new portal block spawns sometimes, it could be a block or two in the mining dimension. in the overworld I can see a block in the distance too. The first block stays where it spawns though.

**Steps to reproduce the issue**
1. Go to mining dimension
2. Go to overworld
3. Repeat 1 and 2 until multiple block start spawning.

**Expected behavior**
When going to the mining dimension I would spawn on the first block.

**Log files**
https://gist.github.com/JanneVed/0cb0a909464240904a49ac45aaffb7f6

**Versions**
- 1.16.5
- Forge - 36.2.39
- 1.0.6

**Other mods**
https://pastebin.com/xLJ1RVV0

**Screenshots (Optional)**
![2023-08-05_21 29 55](https://github.com/henkelmax/advanced-mining-dimension/assets/85487790/c3b2b6c3-7f5c-47c9-b357-b2be1c72c7f3)
![2023-08-05_21 29 28](https://github.com/henkelmax/advanced-mining-dimension/assets/85487790/1b94a5e8-bb66-4d82-8845-e63d34b722d7)

**Comment by henkelmax** [comment]
This Minecraft version is no longer supported. Does this also happen in 1.19.2, 1.19.4 or 1.20.1?

**Comment by JanneVed** [comment]
![2023-08-05_22 45 54](https://github.com/henkelmax/advanced-mining-dimension/assets/85487790/bd910b28-f026-45c7-b862-9e1fb19bfec6)
![2023-08-05_22 42 16](https://github.com/henkelmax/advanced-mining-dimension/assets/85487790/37182205-4ada-4059-9043-1e79914facc6)
Seems like they do on 1.19.2 as well

**Comment by JanneVed** [comment]
I tested it on 1.20.1 with only this mod installed and I still get the same wierd thing that it spawns a new block.

**Comment by Daltaxy** [comment]
Personally, on 1.19.2, it happens as well.
However, I simply destroyed the new portal and it never happened again. (I had a skybase and the portal would spawn at sea level)

**Comment by JanneVed** [comment]
after an intense testing I found out what was causing the bug. Placing a torch on the block caused it to spawn new blocks. Though the extra block in the overworld still spawns on all versions I tested (1.16.5 modded, 1.16.5 only mining dimension, 1.19.2 modded, 1.20.1 only mining dimension).
