### ISSUE TITLE
Creat Mod ores do not generate

### ISSUE THREAD

**Issue by Crystalfor1** [henkelmax/advanced-mining-dimension#76]
The Ores added by the create mod sadly don't generate.

**Steps to reproduce the issue**
1. use the Teleporter

**Expected behavior**
Both Vanilla and modded ores should spawn.

**Versions**
- 1.19.2
- 43.2.11
- 1.20.2
**Other mods**
Create

**Comment by Daltaxy** [comment]
you can add the ores by yourself using the datapack feature, I'm sure most ores don't spawn except Mekanism ores from what I've experienced
