### ISSUE TITLE
"more_ores" can't be apply on 1.20.2 version

### ISSUE THREAD

**Issue by lonerfscar** [henkelmax/advanced-mining-dimension#79]
the datapack "more_ores" can't be apply on 1.20.2 version, how can I config the ores in the "default" datapack? THX

**Comment by Daltaxy** [comment]
hey, use this 
https://misode.github.io/

**Comment by henkelmax** [comment]
![image](https://github.com/henkelmax/advanced-mining-dimension/assets/13237524/11418ca1-64c2-4732-ab71-26027a96f2b8)
