### ISSUE TITLE
Doesn't generate ores from other mods

### ISSUE THREAD

**Issue by Antaiir** [henkelmax/advanced-mining-dimension#80]
Hi there,

**Bug description**
We use this on mc 1.20.1 dedicated server, and even after several hours of intense mining we couldn't find a single or from mods like "Mekanism".

**Versions**
- Minecraft version 1.20.1
- Mod loader Forge
- Mod loader version 47.2.20
- Mod version 1.0.4

**Other mods**
Applied Energistics 2, Balm, BiomeInfo, Collective, Create, GUI Clock, Inventory Essentials, Jade, Jade Addons, JEI, JEI Mekanism Multiblocks, Mekanism (+Additions, Generators, Tools), OptiFine, Patchouli, Waystones, Xaero's World Map, Xaero's Minimap, Xaero's Map - Waystones Compatibility

Thanks in advance!

**Comment by henkelmax** [comment]
You'd need to add other ores with a datapack then. This mod just adds the teleporter. The dimension is just a datapack thats built in to the mod.

**Comment by Antaiir** [comment]
Ah thanks for your fast reply! I'll try that then. :-)

**Comment by JLSkyzer** [comment]
can i have an example to add modded ore ? there is no example

**Comment by hanni79** [comment]
Greetings, I have the same problem. Back in 1.16 I created a datapack from the jar file and added the ores I needed under features, like "manaandartifice:ore_vinteum",
The name of that specific ore changed to "mna:vinteum_ore" as the debug info (and the creator) told me. 
Creating the datapack from the jar lets me start Minecraft as expected and I can load the world without problem. But as soon as I add the line "mna:vinteum_ore", it tells me "Errors i
n currently selected data packs prevented the world from loading". Can someone explain how this works now? Or could you add a new datapack with one or two often used ores (don't know, reactors, Thermal, Industrial or something like that), so people can learn how to do it properly? 

      "minecraft:disk_gravel",
      "minecraft:glow_lichen",
      "minecraft:ore_emerald",
      **"mna:vinteum_ore"**  <- This line immediately prevents the datapack from working, in 1.16 this was all I added to have vinteum ore in the mining dim
    ]
  ]
}

**Comment by calvinthefreak** [comment]
The Issue is still present... any update on this?
If I am correct, it would be enouhg to add ``forge:ores`` to generate the missing ores from the Mods?

Or am I wrong?

Whats the Correct way, to just create a replica of the ``minecraft:overworld`` just as Mining-World? @henkelmax

**Comment by Daltaxy** [comment]
simply use a datapack generator to make sure your syntax is okay; make sure you get the correct mod and ore tags.
Using that I was able to generate not only modded ores (Mystical Agriculture ores for instance), but also generate beautiful lush caves by adding the tag to the datapack

https://misode.github.io/worldgen/

make sure you choose the right (your) minecraft version on the website.
to find ore tags like `mysticalagriculture:inferium_ore` (idk if this one is correct) you may use F3+H while hovering over an ore in-game
you can always delete the mining dimension from your world, so keep playing and tweaking with your datapack to generate the perfect cave

**Comment by ParadoxLeon** [comment]
Hi, I wanted to add ExtremeReactors ores but I always run into issues.
I used the default template and run it trough misode's generator to validate but I always end up with errors.
Can someone share his datapack to identifying my issue?

**Comment by Daltaxy** [comment]
> Hi, I wanted to add ExtremeReactors ores but I always run into issues. I used the default template and run it trough misode's generator to validate but I always end up with errors. Can someone share his datapack to identifying my issue?

hey, what minecraft version? also forge, fabric?

**Comment by ParadoxLeon** [comment]
Using neoforge 1.20.1

**Comment by Daltaxy** [comment]
> Using neoforge 1.20.1

![image](https://github.com/user-attachments/assets/9a1458aa-16fb-4d62-81a2-6919b4e3b082)

open the mod .jar (in /mods of your instance) with winrar, edit the /data/mining_dimension/worldgen/biome/mining.json
add the ores
![image](https://github.com/user-attachments/assets/91a78dac-946f-43f1-8b89-d50df02bb16d)
the ones for the nether or the end don't seem to work obviously... if you wanna change that, generate an alternative end or nether dimension
remember to make backups if you try

preferably to make this work now, remember to delete your mining dimension folder before going back in

**Comment by ParadoxLeon** [comment]
thx it worked <3

**Comment by henkelmax** [comment]
> open the mod .jar (in /mods of your instance) with winrar, edit the /data/mining_dimension/worldgen/biome/mining.json
add the ores

Thats NOT how you should do that. Use datapacks! Never edit stuff in a jar file.
