### ISSUE TITLE
crash the world when removing the mod from my modpack

### ISSUE THREAD

**Issue by BDAgamerPT** [henkelmax/advanced-mining-dimension#81]
### Bug description

When I try to remove the mod from my personal server the world does not open. (yes I removed all blocks from the mod)

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.4

### Mod loader and version

Forge 47.2.20

### Steps to reproduce

just try to open the world and does not open

### Expected behavior

That opens without the mod

### Log files

https://gist.github.com/BDAgamerPT/166b0ce38d9b472a616ae7444c1581c3

### Screenshots

I only have one of the log I sent

**Comment by henkelmax** [comment]
You'd need to remove the dimension aswell.

**Comment by BDAgamerPT** [comment]
First thanks for the help and second how can I remove the dimension?

**Comment by henkelmax** [comment]
Delete the `mining_dimension` folder in the dimension folder and delete everything related to the mining dimension in the `level.dat`. Use a tool loke NBTEdit. You'd need to look for `WorldGenSettings` and `DataPacks` in the level.dat
