### ISSUE TITLE
Invalid datapack no_mobs 

### ISSUE THREAD

**Issue by SpittingBull** [henkelmax/advanced-mining-dimension#83]
### Bug description

When I try adding the example data pack _no_mobs_ to a new world it is marked as incompatible. When I ignore this and still try to add it the error "_Data pack validation failed_" is shown.

### Minecraft version

1.19.2

### Mod version

1.19.2-1.1.0

### Mod loader and version

Forge 4.3.3.8

### Steps to reproduce

1. Create new world
2. Add the data pack no_mobs from [(https://github.com/henkelmax/advanced-mining-dimension/tree/master/datapacks)]

### Expected behavior

The data pack no_mobs should be loaded without any errors.

### Log files

n/a

**Comment by henkelmax** [comment]
![image](https://github.com/henkelmax/advanced-mining-dimension/assets/13237524/7b9af9f4-bad9-4a45-a94b-a53836861a03)

**Comment by hanni79** [comment]
> "These data packs are compatible with version 1.16.2-1.0.1 up to 1.16.5-1.0.6."
> 
> Use https://misode.github.io/ to make your own make sure to select the right version (1.19.2)

How ???
