### ISSUE TITLE
Modded ores not spawning 1.16.3

### ISSUE THREAD

**Issue by ClaudiusMinimus** [henkelmax/advanced-mining-dimension#9]
**Bug description**
Modded ores not spawning. Only vanilla ores spawn. The overworld spawns all the ores just fine.

**Steps to reproduce the issue**
1. Load mods that generate ores with the Mining Dimension

**Expected behavior**
Modded ores should spawn

**Log files**
[latest.log](https://github.com/henkelmax/advanced-mining-dimension/files/5250080/latest.log)

**Versions**
- Minecraft version 1.16.3
- Forge version 34.0.9
- Mod version mining_dimension-1.16.3-1.0.1

**Other mods**
- additional_lights-1.16.3-2.1.2
- AI-Improvements-1.16.2-0.3.0
- AmbientSounds_v3.0.21_mc1.16.2
- angelring-1.16.3-1.3.3
- Apotheosis-1.16.2-4.2.0
- AppleSkin-mc1.16.2-forge-1.0.14
- AutoRestart-1.16.3-1.0.0
- BasaltBlocks-1.16.3-1.0.0
- BetterCaves-1.16.2-1.0.2
- BetterMineshaftsForge-1.16.2-1.0
- bluepower-1.16.3-0.5.219-alpha-universal
- Bookshelf-1.16.3-8.0.5
- borderless-1.16.3-1.1.0
- BotanyPots-1.16.3-5.0.1
- branders-spawnermod-1.16.2-1.6.6
- BridgeMaker-1.16.3-1.0.0
- buildinggadgets-3.7.0
- bwncr-1.16.3-3.8.15
- cc-tweaked-1.16.3-1.92.0
- ceramicbucket-2.0.6-1.16.2+
- clayconversion-1.16.x-1.4
- ClickMachine-1.16.2-4.1.0
- ClientTweaks_1.16.2-5.1.1
- cloth-config-forge-4.1.0
- Clumps-6.0.0.10
- Coins-1.16.3-4.0.2
- comforts-forge-1.16.2-4.0.0.0
- Compressium-1.16.3-1.0.29
- constructionwand-1.16.2-1.3
- Controlling-7.0.0.5
- CookingForBlockheads_1.16.2-9.1.1
- CraftingCraft_1.16.2-9.1.0
- craftingstation-4.1.0
- CraftingTweaks_1.16.2-12.1.1
- CraftTweaker-1.16.3-7.0.0.40
- crashutilities-3.4
- Cucumber-1.16.2-4.1.1
- Cucumber-1.16.3-4.1.2
- curios-forge-1.16.3-4.0.1.0
- customquests-1.16.2-1.0.0
- Cyclic-1.16.3-0.7.1
- dankstorage-3.10c
- DarkUtilities-1.16.3-6.0.1
- DefaultOptions_1.16.2-12.1.1
- DimStorage-1.16.3-4.2.0
- EasierSleeping-1.16.3-1.0.0
- EasySteel-1.16.3-1.2.4
- EditSign-Forge-1.16.3-2.1.2
- elevatorid-1.16.3-1.7.5
- EnchantmentDescriptions-1.16.3-5.0.1
- enderchests-1.16-1.7.3
- endertanks-1.16-1.9.3
- engineersdecor-1.16.3-1.1.2-b7
- engineerstools-1.16.3-1.1.0-b5
- essentials-1.16.2-2.9.1
- extratags-2.2
- extremeSoundMuffler-2.1.1_Forge-1.16.2
- FallingTree-Forge-1.16.3-2.3.1
- fancymenu_1.4.6.1_MC_1.16.2.jar
- FarmingForBlockheads_1.16.2-7.1.1
- FastLeafDecay-v25
- flatbedrock-1.16.3-1.1.3
- FpsReducer-mc1.16.3-1.18
- ftb-chunks-1.1.1.34
- ftb-gui-library-1.0.0.18
- ftb-teams-1.0.1.12
- ftb-ultimine-1.1.0.10
- glassential-forge-1.16.3-1.1.5
- globalxp-1.16.2-v1.4.13
- Gobber2-1.16.3-2.3.9
- grapple_hooks-1.2.2-32
- gravestone-1.16.3-1.0.0
- GreaterEye-1.16.3-1.1.1
- grid-1.16.2-forge33.0.5-1.6.1
- harvest-1.16.2-1.0.3
- industrial-foregoing-1.16.3-3.1.0-7b7cd48
- InventoryEssentials_1.16.2-2.1.0
- invtweaks-1.16.2-1.0.0
- itemcollectors-1.0.5-mc1.16.3
- jei-1.16.2-7.3.2.25
- jeiintegration_1.16.3-6.0.0.8
- JustEnoughResources-1.16.2-0.12.0.99
- kotlin_libraries-1.0-5
- Krate-1.16.3-0.1.1
- kubejs-2.8.0.65
- LargeFluidTank-16.0.4
- LightingWand-1.16.2-1.7.0
- Lollipop-1.16.3-3.2.0
- LostTrinkets-1.16.3-0.1.1
- mahoutsukai-1.16.3-v1.23.2
- mcjtylib-1.16-5.0.7
- metalbarrels-3.3a
- mining_dimension-1.16.3-1.0.1
- mining-helmet-1.16.3-1.0.8
- moreoverlays-1.18.7-mc1.16.2
- Morpheus-1.16.3-4.2.59
- MouseTweaks-2.13-mc1.16.2
- MysticalAgradditions-1.16.3-4.1.0
- MysticalAgriculture-1.16.3-4.1.0
- MysticalCustomization-1.16.3-2.1.0
- NaturesCompass-1.16.2-1.8.5
- NetherPortalFix_1.16.2-7.1.0
- OpenLoader-1.16.3-7.0.1
- overloadedarmorbar-5.1.0
- OverpowderedPickles-1.16.3-1.1.0
- PackingTape-1.16.2-0.9.7
- PassthroughSigns-1.16.2-2.3.6
- Patchouli-1.16.2-43
- PickleTweaks-1.16.2-5.1.1
- Placebo-1.16.2-4.2.0
- platforms-1.16-1.7.4
- polymorph-forge-1.16.2-0.14
- potionsmaster-0.1.21-1.16.3-34.0.9
- Powah-1.16.3-2.3.0
- PowderPower-1.16.3-3.2.6
- PowderPower-1.16.3-3.2.7
- rad-1.16-4.1.0
- rangedpumps-0.8.1
- reap-1.16.3-1.0.0
- refinedstorage-1.9.5
- refinedstorageaddons-0.7.1
- ResourcefulTools-1.16.3-1.2.4
- rftoolsbase-1.16-2.0.5
- rftoolsbuilder-1.16-3.0.5
- rftoolscontrol-1.16-4.0.5
- rftoolspower-1.16-3.0.6
- rftoolsstorage-1.16-2.0.5
- rftoolsutility-1.16-3.0.8
- rsgauges-1.16.3-1.2.4-b8
- ScalableCatsForce-2.13.3-build-3-with-library
- scuba-gear-1.16.3-1.0.1
- ServerTabInfo-1.16.3-1.3.2
- shetiphiancore-1.16-3.8.2
- shutdowner-1.8
- SimpleDivingGear-5.0.3+mc+1.16.3
- simplemagnets-1.0.7-mc1.16.3
- SimpleStorageNetwork-1.16.2-1.0.1
- SolarFluxReborn-1.16.3-16.1.1
- speedyhoppers-1.16.3-1
- StorageDrawers-1.16.2-8.1.0
- strongfarmland-1.16.2-1.1.0
- structurize-0.13.67-ALPHA
- tgcropesmod-1.16.2-1.1.0
- theoneprobe-1.16-3.0.4-beta
- TheVeggieWay-1.16.3-2.2.4
- Tiny-Coal-1.16.3-1.0.0
- titanium-1.16.3-3.1.0
- ToastControl-1.16.2-4.2.0
- torchmaster-2.3.3-alpha
- Trapcraft-1.16.3-3.2.1
- TrashSlot_1.16.2-12.1.0
- travellersboots-1.16.x-1.4.3
- u_team_core-1.16.3-3.1.9.181
- useful_backpacks-1.16.3-1.11.5.82
- Waystones_1.16.2-7.2.0
- WitherSkeletonTweaks-1.16.3-5.1.1
- WorldEdit-CUI-FE3-1.16.2-3.0.7
- worldedit-forge-mc1.16.3-7.2.0-beta-05
- Xaeros_Minimap_20.22.0_Forge_1.16.3
- XaerosWorldMap_1.10.4_Forge_1.16.3
- xnet-1.16-3.0.7

**Comment by henkelmax** [comment]
There unfortunately is not much I can do about that. It depends on the implementation of the ore mod.
The best thing would be to create a datapack that manually adds the ores to the dimension.
If you have any other suggestions, let me know.

**Comment by ClaudiusMinimus** [comment]
I see what you mean. I just added Immersive Engineering and it generates ores. I'll contact the devs of the mods to be sure they make their mods compatible. Thanks!

**Comment by ClaudiusMinimus** [comment]
One last thing. Do you have an example of adding ores with a datapack?

**Comment by henkelmax** [comment]
[This](https://github.com/henkelmax/advanced-mining-dimension/tree/master/datapacks) should help.

**Comment by ClaudiusMinimus** [comment]
I've played with your datapacks as suggested and wondered if you could add some definitions for the following:
From more_ores/data/mining_dimension/worldgen/configured_feature/ore_coal.json
- Line 16: "size": 34
- Line 40: "count": 40

From: more_ores/data/mining_dimension/worldgen/biome/mining.json
Lines 39-41
```
      "minecraft:disk_sand",
      "minecraft:disk_clay",
      "minecraft:disk_gravel"
```
I have not seen nor been able to find reference to disk_[name] or how to use it in a json for configured_feature.

Also, I have not been able to get clay to spawn at all. I have tried with and without the datapack.

**Comment by henkelmax** [comment]
> I've played with your datapacks as suggested and wondered if you could add some definitions for the following:
> **From more_ores/data/mining_dimension/worldgen/configured_feature/ore_coal.json**
> 
> * Line 16: "size": 34
> * Line 40: "count": 40
> 
> **From: more_ores/data/mining_dimension/worldgen/configured_feature/ore_lapis.json**
> 
> * Line 20: "baseline": 32
> * Line 21: "spread": 32
> 
> ```
>           "config": {
>             "baseline": 32,
>             "spread": 32
>           },
> ```

This is just vanilla Minecraft. See [this](https://github.com/slicedlime/examples/blob/master/vanilla_worldgen.zip)

> **From: more_ores/data/mining_dimension/worldgen/biome/mining.json**
> 
> * Lines 39-41
> 
> ```
>       "minecraft:disk_sand",
>       "minecraft:disk_clay",
>       "minecraft:disk_gravel"
> ```
> 
> I have not seen nor been able to find reference to disk_[name] or how to use it in a json for configured_feature.
> 
> Also, I have not been able to get clay to spawn at all. I have tried with and without the datapack.

Same as above. It is located in `/worldgen/configured_feature/`
